# Generated by Django 3.2 on 2021-06-18 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rating',
            field=models.CharField(choices=[('-------', '-------'), ('1', '☆'), ('2', '☆☆'), ('3', '☆☆☆'), ('4', '☆☆☆☆'), ('5*', '☆☆☆☆☆')], default='-------', max_length=200),
        ),
    ]
