# Generated by Django 3.2 on 2021-06-19 11:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0003_alter_rate_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rating',
            field=models.CharField(choices=[('-', '-'), ('1', '☆'), ('2', '☆☆'), ('3', '☆☆☆'), ('4', '☆☆☆☆'), ('5', '☆☆☆☆☆')], default='-------', max_length=200),
        ),
        migrations.AlterField(
            model_name='rate',
            name='username',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rating', to=settings.AUTH_USER_MODEL),
        ),
    ]
