# Generated by Django 3.2 on 2021-06-19 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0004_auto_20210619_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('flexibility', models.IntegerField()),
                ('fitness', models.IntegerField()),
                ('aerobic', models.IntegerField()),
                ('username1', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Fit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
