# Generated by Django 3.2 on 2021-06-19 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_fit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fit',
            old_name='username1',
            new_name='username',
        ),
    ]
