# Generated by Django 3.2 on 2021-06-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_registeration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeration',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registeration',
            name='phonenumber',
            field=models.IntegerField(),
        ),
    ]
