# Generated by Django 3.2 on 2021-06-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20210619_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeration',
            name='offer',
            field=models.CharField(choices=[('Gold', 'Gold  ₹5999'), ('Silver', 'Silver  ₹3999'), ('Bronze', 'Bronze  ₹3999')], default='Gold  ₹1999', max_length=20),
        ),
    ]
