# Generated by Django 3.2 on 2021-06-19 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0009_alter_registeration_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='registeration',
            name='username',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Register', to=settings.AUTH_USER_MODEL),
        ),
    ]
