# Generated by Django 3.2 on 2021-06-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_registeration_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rating',
            field=models.CharField(choices=[('-', '-'), ('1', '☆'), ('2', '☆☆'), ('3', '☆☆☆'), ('4', '☆☆☆☆'), ('5', '☆☆☆☆☆')], default='-', max_length=200),
        ),
    ]
