# Generated by Django 3.2 on 2021-06-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_alter_rate_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='fit',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('OTHERS', 'OTHERS')], default='MALE', max_length=20),
        ),
    ]
