# Generated by Django 3.2 on 2021-06-21 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_alter_registeration_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fit',
            name='username',
        ),
    ]
