# Generated by Django 3.2 on 2021-06-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_remove_fit_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='fit',
            name='username',
            field=models.CharField(default='YOUR FULL NAME', max_length=30),
        ),
    ]
