# Generated by Django 3.0.2 on 2021-06-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_fit_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fit',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registeration',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
