# Generated by Django 3.0.2 on 2021-06-22 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_auto_20210622_2317'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
