# Generated by Django 3.0.2 on 2021-06-23 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_auto_20210623_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fit',
            name='username',
        ),
    ]
