# Generated by Django 3.0.2 on 2021-06-23 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0027_fit_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeration',
            name='username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Register', to=settings.AUTH_USER_MODEL),
        ),
    ]
